config/routes.rb
Bookmytour::Application.routes.draw do
  
  resources :cabbookings

  resources :cabs

  resources :packagebookings
  get "packagebookings/new" => "packagebookings#new", :as => "bookings" 
  get "users/user_booking" => "users#user_booking", :as => "user_booking" 
  get "login" => "sessions#new", :as => "login" 
  get "sign_up" => "user#new", :as => "sign_up" 
  get "dashboard" => "site#dashboard", :as => "dashboard"
  get "userdashboard" => "site#userdashboard", :as => "userdashboard"
  get "site/index"
  resources :packages
  resources :users
  resources :sessions

  root 'site#index'
  

end

app/models/packagebooking.rb
class Packagebooking < ActiveRecord::Base
	belongs_to :user
	belongs_to :package
	
end

app/controllers/packagebookings_controller.rb
class PackagebookingsController < ApplicationController
  before_action :set_packagebooking, only: [:show, :edit, :update, :destroy]

  # GET /packagebookings
  # GET /packagebookings.json
  def index
    @packagebookings = Packagebooking.all
         respond_to do |format|
          format.html # show.html.erb
          format.json { render :json => @packagebooking }
        end

  end

  # GET /packagebookings/1
  # GET /packagebookings/1.json
  def show
          @packagebooking = Packagebooking.find(params[:id])
          respond_to do |format|
          format.html # show.html.erb
          #format.js
          format.json { render :json => @packagebooking }
          end
  end
   
   
  # GET /packagebookings/new
  def new
    @packagebooking = Packagebooking.new
     respond_to do |format|
          format.html # show.html.erb
          format.json { render :json => @packagebooking }
    end
        
  end

  # GET /packagebookings/1/edit
  def edit
    @packagebooking = Packagebooking.find(params[:id])
  end

  # POST /packagebookings
  # POST /packagebookings.json
  def create
    @packagebooking = Packagebooking.new(packagebooking_params)

    respond_to do |format|
      if @packagebooking.save
        format.html { redirect_to @packagebooking, notice: 'Packagebooking was successfully created.' }
        format.js
        format.json { render action: 'show', status: :created, location: @packagebooking }
      else
        format.html { render action: 'new' }
        format.js       
        format.json { render json: @packagebooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packagebookings/1
  # PATCH/PUT /packagebookings/1.json
  def update
    @packagebooking = Packagebooking.find(params[:id])
    respond_to do |format|
      if @packagebooking.update(packagebooking_params)
        format.html { redirect_to @packagebooking, notice: 'Packagebooking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @packagebooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packagebookings/1
  # DELETE /packagebookings/1.json
  def destroy
    @packagebooking = Packagebooking.find(params[:id])
    @packagebooking.destroy
    respond_to do |format|
      format.html { redirect_to packagebookings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_packagebooking
      @packagebooking = Packagebooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def packagebooking_params
      params.require(:packagebooking).permit(:user_id, :package_id, :user_name,:amount, :noofperson, :email, :contact, :dob, :doj,:facilities,:tour_package)
    end
end

app/helpers/packagebookings_helper.rb
module PackagebookingsHelper
end

app/views/packagebookings/_form.html.erb
<%= form_for(@packagebooking , :remote => true) do |f| %>
  <% if @packagebooking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@packagebooking.errors.count, "error") %> prohibited this packagebooking from being saved:</h2>

      <ul>
      <% @packagebooking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br>
    <%= f.number_field :package_id %>
  </div>-->
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :tour_package%><br>
    <%= f.select :tour_package,["India","US"] %>
  </div>
  
  <div class="field">
    <%= f.label :facilities%><br>
    <%= f.text_field :facilities %>
  </div>
  <div class="field">
    <%= f.label :noofperson %><br>
    <%= f.number_field :noofperson %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.number_field :contact %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :doj %><br>
    <%= f.date_select :doj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/packagebookings/booking.html.erb
test

app/views/packagebookings/create.js.erb
$(".packagebooking_form_div").html(
	"Thank you for your booking,<br/> we will get back to you soon.");

app/views/packagebookings/edit.html.erb
<h1>Editing packagebooking</h1>

<%= render 'form' %>

<%= link_to 'Show', @packagebooking %> |
<%= link_to 'Back', packagebookings_path %>

app/views/packagebookings/index.html.erb
<%= render :partial => "site/adminmenu" %>
<div class="dashboard-right">
<h1>Listing packagebookings</h1>

<table border="1">
  <thead>
    <tr>
      <th>User</th>
      <th>Package</th>
      <th>Name</th>
      <th>Package</th>
      <th>Amount</th>
      <th>No of person</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Date of Birth</th>
      <th>Date of Joining</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @packagebookings.each do |packagebooking| %>
      <tr>
        <td><%= packagebooking.user_id %></td>
        <td><%= packagebooking.package_id %></td>
        <td><%= packagebooking.user_name %></td>
        <td><%= packagebooking.tour_package%></td>
        <td><%= packagebooking.amount %></td>
        <td><%= packagebooking.noofperson %></td>
        <td><%= packagebooking.email %></td>
        <td><%= packagebooking.contact %></td>
        <td><%= packagebooking.dob %></td>
        <td><%= packagebooking.doj %></td>
        <td><%= link_to 'Show', packagebooking %></td>
        <td><%= link_to 'Edit', edit_packagebooking_path(packagebooking) %></td>
        <td><%= link_to 'Destroy', packagebooking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Packagebooking', new_packagebooking_path %>
</div>

app/views/packagebookings/new.html.erb
<h1>New packagebooking</h1>

<%= render 'form' %>

<%= link_to 'Back', packagebookings_path %>

app/views/packagebookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @packagebooking.user_id %>
</p>

<p>
  <strong>Package:</strong>
  <%= @packagebooking.package_id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @packagebooking.user_name %>
</p>
<p>
  <strong>Tour Package:</strong>
  <%= @packagebooking.tour_package %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @packagebooking.amount %>
</p>

<p>
  <strong>Noofperson:</strong>
  <%= @packagebooking.noofperson %>
</p>

<p>
  <strong>Email:</strong>
  <%= @packagebooking.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @packagebooking.contact %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @packagebooking.dob %>
</p>

<p>
  <strong>Date of journey:</strong>
  <%= @packagebooking.doj %>
</p>

<%= link_to 'Edit', edit_packagebooking_path(@packagebooking) %> |
<%= link_to 'Back', packagebookings_path %>