config/routes.rb
Bookmytour::Application.routes.draw do
  
  resources :cabbookings

  resources :cabs

  resources :packagebookings
  get "packagebookings/new" => "packagebookings#new", :as => "bookings" 
  get "users/user_booking" => "users#user_booking", :as => "user_booking" 
  get "login" => "sessions#new", :as => "login" 
  get "sign_up" => "user#new", :as => "sign_up" 
  get "dashboard" => "site#dashboard", :as => "dashboard"
  get "userdashboard" => "site#userdashboard", :as => "userdashboard"
  get "site/index"
  resources :packages
  resources :users
  resources :sessions

  root 'site#index'
  

end

app/models/cab.rb
class Cab < ActiveRecord::Base
	has_many :cabbooking
  	has_many :user, through: :cabbooking
end

app/controllers/cabs_controller.rb
class CabsController < ApplicationController
  before_action :set_cab, only: [:show, :edit, :update, :destroy]

  # GET /cabs
  # GET /cabs.json
  def index
    @cabs = Cab.all
  end

  # GET /cabs/1
  # GET /cabs/1.json
  def show
  end

  # GET /cabs/new
  def new
    @cab = Cab.new
  end

  # GET /cabs/1/edit
  def edit
  end

  # POST /cabs
  # POST /cabs.json
  def create
    @cab = Cab.new(cab_params)

    respond_to do |format|
      if @cab.save
        format.html { redirect_to @cab, notice: 'Cab was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cab }
      else
        format.html { render action: 'new' }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabs/1
  # PATCH/PUT /cabs/1.json
  def update
    respond_to do |format|
      if @cab.update(cab_params)
        format.html { redirect_to @cab, notice: 'Cab was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabs/1
  # DELETE /cabs/1.json
  def destroy
    @cab.destroy
    respond_to do |format|
      format.html { redirect_to cabs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cab
      @cab = Cab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cab_params
      params.require(:cab).permit(:cab_name, :cab_type, :cab_number, :cab_rate, :cab_running, :cab_status, :cab_company)
    end
end

app/helpers/cabs_helper.rb
module CabsHelper
end

app/views/cabs/_form.html.erb
<%= form_for(@cab) do |f| %>
  <% if @cab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cab.errors.count, "error") %> prohibited this cab from being saved:</h2>

      <ul>
      <% @cab.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cab_name %><br>
    <%= f.text_field :cab_name %>
  </div>
  <div class="field">
    <%= f.label :cab_type %><br>
    <%= f.text_field :cab_type %>
  </div>
  <div class="field">
    <%= f.label :cab_number %><br>
    <%= f.text_field :cab_number %>
  </div>
  <div class="field">
    <%= f.label :cab_rate %><br>
    <%= f.text_field :cab_rate %>
  </div>
  <div class="field">
    <%= f.label :cab_running %><br>
    <%= f.number_field :cab_running %>
  </div>
  <div class="field">
    <%= f.label :cab_status %><br>
    <%= f.text_field :cab_status %>
  </div>
  <div class="field">
    <%= f.label :cab_company %><br>
    <%= f.text_field :cab_company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabs/edit.html.erb
<h1>Editing cab</h1>

<%= render 'form' %>

<%= link_to 'Show', @cab %> |
<%= link_to 'Back', cabs_path %>

app/views/cabs/index.html.erb
<%= render :partial => "site/adminmenu" %>
<div class="dashboard-right">

<h1>Listing cabs</h1>

<table border="1">
  <thead>
    <tr>
      <th>Cab name</th>
      <th>Cab type</th>
      <th>Cab number</th>
      <th>Cab rate</th>
      <th>Cab running</th>
      <th>Cab status</th>
      <th>Cab company</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cabs.each do |cab| %>
      <tr>
        <td><%= cab.cab_name %></td>
        <td><%= cab.cab_type %></td>
        <td><%= cab.cab_number %></td>
        <td><%= cab.cab_rate %></td>
        <td><%= cab.cab_running %></td>
        <td><%= cab.cab_status %></td>
        <td><%= cab.cab_company %></td>
        <td><%= link_to 'Show', cab %></td>
        <td><%= link_to 'Edit', edit_cab_path(cab) %></td>
        <td><%= link_to 'Destroy', cab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cab', new_cab_path %>
</div>

app/views/cabs/new.html.erb
<h1>New cab</h1>

<%= render 'form' %>

<%= link_to 'Back', cabs_path %>

app/views/cabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cab name:</strong>
  <%= @cab.cab_name %>
</p>

<p>
  <strong>Cab type:</strong>
  <%= @cab.cab_type %>
</p>

<p>
  <strong>Cab number:</strong>
  <%= @cab.cab_number %>
</p>

<p>
  <strong>Cab rate:</strong>
  <%= @cab.cab_rate %>
</p>

<p>
  <strong>Cab running:</strong>
  <%= @cab.cab_running %>
</p>

<p>
  <strong>Cab status:</strong>
  <%= @cab.cab_status %>
</p>

<p>
  <strong>Cab company:</strong>
  <%= @cab.cab_company %>
</p>

<%= link_to 'Edit', edit_cab_path(@cab) %> |
<%= link_to 'Back', cabs_path %>