config/routes.rb
Bookmytour::Application.routes.draw do
  
  resources :cabbookings

  resources :cabs

  resources :packagebookings
  get "packagebookings/new" => "packagebookings#new", :as => "bookings" 
  get "users/user_booking" => "users#user_booking", :as => "user_booking" 
  get "login" => "sessions#new", :as => "login" 
  get "sign_up" => "user#new", :as => "sign_up" 
  get "dashboard" => "site#dashboard", :as => "dashboard"
  get "userdashboard" => "site#userdashboard", :as => "userdashboard"
  get "site/index"
  resources :packages
  resources :users
  resources :sessions

  root 'site#index'
  

end

app/models/cabbooking.rb
class Cabbooking < ActiveRecord::Base
	belongs_to :user
	belongs_to :cab
end

app/controllers/cabbookings_controller.rb
class CabbookingsController < ApplicationController
  before_action :set_cabbooking, only: [:show, :edit, :update, :destroy]

  # GET /cabbookings
  # GET /cabbookings.json
  def index
    @cabbookings = Cabbooking.all
  end

  # GET /cabbookings/1
  # GET /cabbookings/1.json
  def show
  end

  # GET /cabbookings/new
  def new
    @cabbooking = Cabbooking.new
  end

  # GET /cabbookings/1/edit
  def edit
  end

  # POST /cabbookings
  # POST /cabbookings.json
  def create
    @cabbooking = Cabbooking.new(cabbooking_params)

    respond_to do |format|
      if @cabbooking.save
        format.html { redirect_to @cabbooking, notice: 'Cabbooking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cabbooking }
      else
        format.html { render action: 'new' }
        format.json { render json: @cabbooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabbookings/1
  # PATCH/PUT /cabbookings/1.json
  def update
    respond_to do |format|
      if @cabbooking.update(cabbooking_params)
        format.html { redirect_to @cabbooking, notice: 'Cabbooking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cabbooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabbookings/1
  # DELETE /cabbookings/1.json
  def destroy
    @cabbooking.destroy
    respond_to do |format|
      format.html { redirect_to cabbookings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabbooking
      @cabbooking = Cabbooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cabbooking_params
      params.require(:cabbooking).permit(:cab_id, :user_id, :user_name,:cab_from, :cab_to, :booking_date, :noofperson,:cab_trip, :amount)
    end
end

app/helpers/cabbookings_helper.rb
module CabbookingsHelper
end

app/views/cabbookings/_form.html.erb
<%= form_for(@cabbooking) do |f| %>
  <% if @cabbooking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabbooking.errors.count, "error") %> prohibited this cabbooking from being saved:</h2>

      <ul>
      <% @cabbooking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cab_id %><br>
    <%= f.number_field :cab_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :cab_from %><br>
    <%= f.text_field :cab_from %>
  </div>
  <div class="field">
    <%= f.label :cab_to %><br>
    <%= f.text_field :cab_to %>
  </div>
  <div class="field">
    <%= f.label :booking_date %><br>
    <%= f.date_select :booking_date %>
  </div>
  <div class="field">
    <%= f.label :noofperson %><br>
    <%= f.number_field :noofperson %>
  </div>
   <div class="field">
    <%= f.label :cab_trip %><br>
    <%= f.text_field :cab_trip %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabbookings/edit.html.erb
<h1>Editing cabbooking</h1>

<%= render 'form' %>

<%= link_to 'Show', @cabbooking %> |
<%= link_to 'Back', cabbookings_path %>

app/views/cabbookings/index.html.erb
<%= render :partial => "site/adminmenu" %>
<div class="dashboard-right">
<h1>Listing cabbookings</h1>

<table border="1">
  <thead>
    <tr>
      <th>Cab</th>
      <th>User</th>
      <th>User Name </th>
      <th>Cab from</th>
      <th>Cab to</th>
      <th>Booking date</th>
      <th>Noofperson</th>
       <th>Cab Trip</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>iv
    </tr>
  </thead>

  <tbody>
    <% @cabbookings.each do |cabbooking| %>
      <tr>
        <td><%= cabbooking.cab_id %></td>
        <td><%= cabbooking.user_id %></td>
        <td><%= cabbooking.user_name %></td>
        <td><%= cabbooking.cab_from %></td>
        <td><%= cabbooking.cab_to %></td>
        <td><%= cabbooking.booking_date %></td>
        <td><%= cabbooking.noofperson %></td>
         <td><%= cabbooking.cab_trip %></td>
        <td><%= cabbooking.amount %></td>
        <td><%= link_to 'Show', cabbooking %></td>
        <td><%= link_to 'Edit', edit_cabbooking_path(cabbooking) %></td>
        <td><%= link_to 'Destroy', cabbooking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cabbooking', new_cabbooking_path %>
</div>

app/views/cabbookings/new.html.erb
<h1>New cabbooking</h1>

<%= render 'form' %>

<%= link_to 'Back', cabbookings_path %>

app/views/cabbookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cab:</strong>
  <%= @cabbooking.cab_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @cabbooking.user_id %>
</p>

<p>
  <strong>Cab from:</strong>
  <%= @cabbooking.cab_from %>
</p>

<p>
  <strong>Cab to:</strong>
  <%= @cabbooking.cab_to %>
</p>

<p>
  <strong>Booking date:</strong>
  <%= @cabbooking.booking_date %>
</p>

<p>
  <strong>Noofperson:</strong>
  <%= @cabbooking.noofperson %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cabbooking.amount %>
</p>

<%= link_to 'Edit', edit_cabbooking_path(@cabbooking) %> |
<%= link_to 'Back', cabbookings_path %>